app:
  - sign_up
  - sign_in

user:
  - create_workspace
  - create_history
  - create_document
  - upload_project

project:
  - rename
  - follow

workspace:
  - rename
  - append
  - reorder
  - delete

history:
  - rename
  - delete

document:
  - create
  - update
  - delete
