user:
  username:
    type: string

project:
  remote:
    type: string

project:
  name:
    type: string

document:
  title:
    type: string

document:
  content:
    type: string

file:
  content:
    type: string
